### ISSUE TITLE
Extract WebTransport related code from datagram-frame

### ISSUE THREAD

**Issue by LPardue** [LPardue/quiche#3]
The `datagram-frame` branch contains stuff related to the WebTransport protocol that will likely undergo a lot of churn. To make life easier, I'd like to that code out into its own branch that builds on top of `datagram-frame`. Unfortunately the commit history isn't as granular as I'd have liked, the WebTransport commit has some other changes peppered in that I'd like to keep.

@xanathar: since you're now working on top of `datagram-frame` how much pain would you feel if I refactored?

**Comment by xanathar** [comment]
No pain at all! 
Feel free to do it. (also, thanks for asking!!)

**Comment by LPardue** [comment]
Closing now that this done (and over 1 year old :D)
